service: sasaki-rfa-logs
app: rfa-logs
org: shingosasaki
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::sasaki-rfa-logs/*"
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "arn:aws:lambda:ap-northeast-1:613226550613:function:sasaki-rfa-logs-dev-imageCreator"
        - "arn:aws:lambda:ap-northeast-1:613226550613:function:sasaki-rfa-logs-dev-cloudVisionDispatcher"
        - "arn:aws:lambda:ap-northeast-1:613226550613:function:sasaki-rfa-logs-dev-db"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:613226550613:table/rfa-logs"
functions:
  observer:
    handler: functions/observer.index
    timeout: 60
  imageCreator:
    handler: functions/imageCreator.index
    timeout: 30
  db:
    handler: functions/db.index
    timeout: 30
  rfa:
    handler: functions/rfa.index
    timeout: 30
    events:
      - s3:
        bucket: sasaki-rfa-logs
        event: s3:ObjectCreated:*
        existing: true

  cloudVisionDispatcher:
    handler: functions/cloudVisionDispatcher.index
    timeout: 30
    environment:
      TOKEN: ${ssm:sasaki-rfa-secret-param}